// Code generated by Prismic. DO NOT EDIT.

import Accordions from "./Accordions";
import Articles from "./Articles";
import Body from "./Body";
import CallToAction from "./CallToAction";
import Faqs from "./Faqs";
import Hero from "./Hero";
import HomePricing from "./HomePricing";
import HomeSecurity from "./HomeSecurity";
import InfoBoxList from "./InfoBoxList";
import Logos from "./Logos";
import Markdown from "./Markdown";
import ReadyToGetStarted from "./ReadyToGetStarted";
import Stats from "./Stats";
import Table from "./Table";
import TeamList from "./TeamList";
import Testimonials from "./Testimonials";
import AlternatingGrid from "./AlternatingGrid";
import Video from "./Video";

export const components = {
	accordions: Accordions,
	articles: Articles,
	body_text: Body,
	call_to_action: CallToAction,
	faqs: Faqs,
	hero: Hero,
	home_pricing: HomePricing,
	home_security: HomeSecurity,
	info_box_list: InfoBoxList,
	logos: Logos,
	markdown: Markdown,
	ready_to_get_started: ReadyToGetStarted,
	stats: Stats,
	table: Table,
	team_list: TeamList,
	testimonials: Testimonials,
	text_image_grid: AlternatingGrid,
	youtube: Video
};